### ISSUE TITLE
Idea: API Extensions

### ISSUE THREAD

**Issue by jrcarl624** [MCBE-Utilities/BeAPI#11]
Basically a npm module can have a setting called "BeApiExtension" where it just runs and puts the contents in a file for BeApi to read from on startup of the world or something. Where it can extend the classes before the globalthis  override is run. This can be useful for adding additional command options to the base BeAPI command handler for example. As there may be modules that add two good features to the same class and you want to use them both without extra imports.

**Comment by nobu-sh** [comment]
Make an example then I will review it.

**Comment by jrcarl624** [comment]
Still working on this, just to note
