### ISSUE TITLE
IDEA, additional events

### ISSUE THREAD

**Issue by jrcarl624** [MCBE-Utilities/BeAPI#12]
OnScore - like on tag

OnDeath - for player

**Comment by ATXLtheAxolotl** [comment]
I’m pretty sure onDeath can be done with animation controllers

**Comment by jrcarl624** [comment]
> I’m pretty sure onDeath can be done with animation controller

Its possible as thats why I suggested it

**Comment by PMK744** [comment]
I'll add a death event today.
