### ISSUE TITLE
Idea: Plugin IPC Related

### ISSUE THREAD

**Issue by jrcarl624** [MCBE-Utilities/BeAPI#14]
I talked to @nobu-sh about this before but... I feel that there should be a couple of default modules that store data on a database so you can access data of offline players and see if the player exists etc. The key would be the player read only name, it could add a uuid to the player as if they change their name but that seems a bit far...
This could have a structure of
```js
//obv the const is just for the example.
const player = {
name: "miner"
nameTag:"Miner7493"
tags:["fish","fishs"]
scores:{timer:100,deaths:4}
// this is the part I'm getting at...
pack:{
  example:{
  data:1
  }
  example2:{
  data:2
  }
}
 
```

On leave it would get all of the tags and scores and sync them to the database as if the player is offline it will check the database for the player for the information. Basically all the data that the player has stored or it stores only basic data like name, name tag and other stuff.

A configuration database made from the configuration of each pack on the would with options to configure each pack without having to re add the pack.

All of these should be able to be enabled/disabled in the main config. As a couple of additional default databases can allow for packs to access the same data.  As it would use the packname (that is passed from the config) as a key name in the default databases. As if packs create separate databases for common things there will come a problem where each pack will add it's own database for players and that will inflate world sizes.

The only thing to really worry about is pack ipc with database saves and writes. I'm

**Comment by jrcarl624** [comment]
I am willing to work on this, I just need approval.

**Comment by PMK744** [comment]
Create it as a module, then I'll check it out.

**Comment by jrcarl624** [comment]
> Create it as a module, then I'll check it out. 

I plan to do that, cool will do.

**Comment by jrcarl624** [comment]
Still working on this, just to note
