### ISSUE TITLE
Scoreboard player names has a limit.

### ISSUE THREAD

**Issue by PMK744** [MCBE-Utilities/BeAPI#15]
Due to scoreboard player names having a character limit, the built in database can only store a small amount of data.

**Comment by nobu-sh** [comment]
It appears to be a Mojang bug where there is officially no character write limit however on world restart it gets cut off at a certain point. 
I will review other methods of possibly temporarily bypassing this.

Mojang implement simple sqlite3 bindings when?

**Comment by nobu-sh** [comment]
Fixed 👍
