### ISSUE TITLE
Proposal: Condensed Binary

### ISSUE THREAD

**Issue by nobu-sh** [MCBE-Utilities/BeAPI#24]
Binary takes up a lot of space and scoreboard player names break after a certain threshold.
The following code example transpiles binary to and from a base 10 storage format by concurrent 0's with numbers higher than 1; In most cases saving up to 30%.
It allows for a temporary solution for storing more data in a document while chunking is being developed.

```ts
/**
 * Binary "condenser" by nobu-sh
 * LICENSE: https://www.apache.org/licenses/LICENSE-2.0
 * 
 * Essentially when working with an alternative way to store
 * persistent data in MCBE we decided to convert our documents
 * to and from binary instead of JSON#stringify.
 * 
 * We chose this method as it led to less issues with conflicting
 * scoreboard names or data.
 * 
 * However, not everything is perfect, binary takes up too much space 
 * so we decided on a new method of binary storage. It takes a tad bit
 * longer to translate data however allows per a lot more storage on
 * a scoreboard players name.
 * 
 * Condensed binary essentially is a encoder/decoder that removes
 * spaces and looks for zeros next to each other and uses base 10
 * to overall condense the binary down a bit more.
 * 
 * Since zeros are more common than ones in binary we are looking
 * at possible total byte reductions of up to 30%!
 */

function strToBin(str: string): string {
  return str.replace(/./g, char => `00${char.charCodeAt(0).toString(2)}`.slice(-8))
}

function binToStr(bin: string): string {
  return bin.replace(/.{8}/g, chunk => String.fromCharCode(parseInt(chunk, 2)))
}

function binToCondensed(bin: string): string {
  return bin.replace(/(0)\1+/g, m => `${m.length}`)
}

function condensedToBin(con: string): string {
  return con.replace(/[2-9]/g, a => Array(+a).fill(0).join(''))
}

console.log("Normal Binary")
const bin = strToBin('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ `1234567890-=~!@#$%^&*()_+\\][;\',./<>?:"{}|')
console.log(bin.length)

const binStr = binToStr(bin)
console.log(binStr)


console.log("Condensed Binary")
const condensed = binToCondensed(bin)
console.log(condensed.length)

const uncondensed = condensedToBin(condensed)
const str = binToStr(uncondensed)
console.log(str)
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/PQKhFgCgAIWghAlgOwIYCcCe0BEBjAe2QBMBTZAZ1PR2gCNtkC6BXAWgoAspZoAZAJIBhAKIA5AMoiAXNE4AXeQAcK04MADuWgHSolqPJ1LaC6AObAANojzkqFYINGSRbAEzaADDzg-oIiipkeURUS0tsDSNkaA1TAGsUM1jEeU5oVBiw+Wo0EIA3UljUbHkCaAoy9FI-JWoKREryeWhiVHlUaBRoAFkheBFYorI8RDJiaDLoQmRC9BaCFnRWgjwWAFtmij8pzImAM3QCdfoUDGwUJtQJgn3oACkJAHkxAGJK9CTEfcxtPz8AOpFQwEKiTTiNaCbNIECaoChdFqWUgTKbIwJdQIsUgIjSpdIzfbWPAhZBmPwUQjVOgEDATNCbBGmVrtVB-GC+DnQAASBA0pDmABpoEwWgLqJg0klMdA6uh9qQScK6GcsJNUPEcdAWEpJgRyusWIYKvpbNAKeV+a1FWMUdAiBkRaQNFDSDCbncVWg1ZVTKgzMZoAIWh1NQjOh0Jir5H5LEQA8spvJ0JkKJZ2sNWXI+eLlmE4xoEXLHXGWutTEVfSmA-bkH5OpSKzS6bL05h6iLUJt2bw-EIiGRKHavedoDigiF8xdw2PkIQyOhgCNYdRwe1oNVy4VtlyKKatXtoHGCPEEftmQAvaigp0ADxD5VIBnSBDSq8PLHs9HhRQAjN4uSmAg5nzaYBzsIo31Ob1sGIPkslOMsKx7TleAkFAzSvI5w2qKEKzA9ZyxiNJMlrLVuhHNUrQwIpj0SMl6xaJRQQaOhkT1DpLHoSUimqYgjRCIgmTuHU9WgABmTwAFIAEIfGAKAoH2Fg50EmIPgAFQIJBkAACg+WQPiSABKQzk2lABvHgNzdJZ1OTbRqiUdNbF04BtGAMxhUMDBoAAXgAPmgAADTxPAAEgsnz0G0aL+zIABBeRdM8YztDKCRzLJXS3GMgBfYLtDTGxSF0tgAA5jOMqA8sUyBlNUxAHS9LTMvQXSvTMz4yVMiosuSKyYBs+Q7OgxzSGcgxSvcizyryzzvM4FT4n8oK2qSbRDmOIROAweLSv0dAqAEYJdMMZbhVyqqarqhqSSamIWoIfsSAg4gOpQLqTK+sloEG6BhtGr1xsm1zgBS4yAB1fwAagWqFVpCyL1m0ZEyTSArqsgWrICUlT7odGZByoYgtJ0s6iB+sxeqM37-sB9AYhmEGXOmgBtNw2AATgAXXhzpAugBL0BTTBdJh1A0v2RBwgh7QACsCBQXSAHIVeu7G6pmCgCGRVGCDMXScDEUx1jCBBVUwHAse1lovX8vr0DJ5WVdQOg8DIfYzAheX4ksdYmCUABHI6RvyDRb0wC8EvgIQABERAAMQAcW5AR7gAaT4HoxCeAAFABFAAlCQNIAVQANQBAANABNAAtELfzccSABYAFYADYAHZyq5zw2D8gA-GSAAFXnCqSAD0ADIQF04yAH0YchyGebZgBuSGVcFDyAB4AoAfmkHALLygAfdWoG13XjDjQ3gbRsw0ix6+hLtlA2odp62o+5AbaErffWD9P7JlfrjSAN89b3yNi9YmdodLnGtm-SgLQiZvW-igLScC3p-wAZQIBMD0FDmIKjcgz9ODgNttqOc4ESEO2ISTZ2elGEonwZUR2mDkCtWTLpfGdCSbsMIQbfSYCgA)

**Comment by jrcarl624** [comment]
I can provide another encoding method if needed, it condenses strings in a different way.

**Comment by nobu-sh** [comment]
It would need to be a 1 byte number solution.

**Comment by nobu-sh** [comment]
This will break current database implementations. Pull requester will need to check encoded string for numbers greater than one and use old binary instead.

Maybe also implement automatic migration of old binary data to condensed binary data...
Just a suggestion though, not required.
