### ISSUE TITLE
Content Log is spammed when a player leaves the world

### ISSUE THREAD

**Issue by ghost** [MCBE-Utilities/BeAPI#25]
___
**BeAPI Core Version**
2.2.1

**Create BeAPI Version**
2.1.1

**MCBE Version**
Production 1.18.10
___

**Describe the bug**
When a player leaves a world (not the owner), the content log gets spammed with 1 of 2 messages, seemingly at random.
Sometimes it's this;
![image](https://user-images.githubusercontent.com/84670775/154262258-fce6d9c3-6b19-4ad5-8731-504acbe44845.png)
Other times it's "Failed to get property 'getEntitiesFromViewVector'"

**To Reproduce**
1. Join a world with BeAPI and GameTest Framework enabled
2. Get an alt or another player to join the world
3. Get the alt or other player to leave
4. See the content log

**Expected behavior**
The content log shouldn't be spammed

**Comment by nobu-sh** [comment]
Fixed in https://github.com/MCBE-Utilities/BeAPI/commit/9ee67779dd66c9b299b9464b2e4a2ebc6b01c2c9
