### ISSUE TITLE
getTags() only returns the second letter of the tags of an entity

### ISSUE THREAD

**Issue by ghost** [MCBE-Utilities/BeAPI#26]
___
**BeAPI Core Version**
2.2.1

**Create BeAPI Version**
2.1.1

**MCBE Version**
Production 1.18.10
___

**Describe the bug**
When running this:
```
client.commands.register({
    name: "ping",
    description: "Test command"
    }, (data) => {
    data.sender.sendMessage("§ePong!")
    for(const [,tags] of data.sender.getTags()) {
        data.sender.sendMessage(tags)
    }
})
```
The message that gets returned is only the second letter of each tag, ie
"a" from "rank"
"w" from "owner"
":" from "o:money"

**To Reproduce**
1. Use a for loop for a getTags() array
2. Give yourself a few random tags
3. Attempt to print each tag
4. Observe only the second letter of each tag is outputted

**Expected behavior**
Every tag should have their whole name and text displayed

**Screenshots**
The last line is after running `/tag @s list`
![image](https://user-images.githubusercontent.com/84670775/154263069-3aa43b78-ef1c-4fd6-afed-efcec610bf38.png)

**Comment by nobu-sh** [comment]
That's an issue with your code, `getTags()` returns a string array, by doing `[, tags]` you are destructuring the string and getting only the second letter.

The correct way would be:
```ts
client.commands.register({
    name: "ping",
    description: "Test command"
    }, (data) => {
    data.sender.sendMessage("§ePong!")
    for(const tag of data.sender.getTags()) {
        data.sender.sendMessage(tag)
    }
})
```
