### ISSUE TITLE
.name doesn't return the Microsoft gamertag so the docs shouldn't say .getName does

### ISSUE THREAD

**Issue by mrpatches123** [MCBE-Utilities/BeAPI#6]
![image](https://user-images.githubusercontent.com/49619048/149636030-8588fa69-47aa-4f15-8071-4a8fe9e60e01.png)

**Comment by nobu-sh** [comment]
This is a known issue and has been patched in [#47b47d4](https://github.com/MCBE-Utilities/BeAPI/commit/47b47d4e043138c30c20b069994d540544ff90a9#diff-bc59605f42a5797c7d4f31a1e0e3f942fa513392cbc3ea52d0b0928f31e51eacR23) for v2
